# Demo 1 Tip Calculation Demo

Each data pipleline follows similar steps being:
1. load
2. inspect
3. parse
4. extract
5. group/average
6. clean up

## Imports and Loading CSV as Dataframe

In [42]:
import pandas as pd

df = pd.read_csv('taxi_data_subset.csv')

## Observe the shape of the dataframe and data types

In [43]:
display(df.shape)

print()

display(df.dtypes)

print()

display(df.dtypes[[
    'tpep_pickup_datetime',
    'fare_amount',
    'tip_amount'
]])

(50000, 20)

VendorID                   int64
tpep_pickup_datetime         str
tpep_dropoff_datetime        str
passenger_count            int64
trip_distance            float64
RatecodeID                 int64
store_and_fwd_flag           str
PULocationID               int64
DOLocationID               int64
payment_type               int64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge      int64
total_amount             float64
congestion_surcharge     float64
Airport_fee              float64
cbd_congestion_fee       float64
dtype: object

tpep_pickup_datetime        str
fare_amount             float64
tip_amount              float64
dtype: object

In [44]:
display(df.head())

print()


display(df.tail())

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1,0.97,1,N,239,238,1,7.2,1.00,0.5,3.66,0.0,1,15.86,2.5,0.0,0.00
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0,0.90,1,N,163,162,2,7.9,4.25,0.5,0.00,0.0,1,13.65,2.5,0.0,0.75
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0,1.40,1,N,43,237,1,10.7,4.25,0.5,2.50,0.0,1,18.95,2.5,0.0,0.75
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4,5.58,1,N,142,209,1,38.7,1.00,0.5,11.11,0.0,1,55.56,2.5,0.0,0.75
4,2,2026-01-01 00:27:13,2026-01-01 00:40:43,0,2.16,1,N,88,144,1,13.5,1.00,0.5,3.85,0.0,1,23.10,2.5,0.0,0.75

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
49995,1,2026-01-01 17:27:10,2026-01-01 17:39:09,1,1.30,1,N,88,45,2,11.4,3.25,0.5,0.00,0.00,1,16.15,2.5,0.00,0.75
49996,1,2026-01-01 17:49:29,2026-01-01 18:00:52,1,4.10,1,N,45,224,1,18.4,3.25,0.5,2.00,0.00,1,25.15,2.5,0.00,0.75
49997,2,2026-01-01 17:03:10,2026-01-01 17:19:26,1,6.65,1,N,138,255,1,28.2,7.50,0.5,7.44,0.00,1,46.39,0.0,1.75,0.00
49998,1,2026-01-01 17:18:13,2026-01-01 17:55:04,1,19.30,2,N,132,116,2,70.0,1.75,0.5,0.00,6.94,1,80.19,0.0,1.75,0.00
49999,2,2026-01-01 17:45:14,2026-01-01 18:02:43,4,2.70,1,N,100,140,1,17.7,2.50,0.5,4.99,0.00,1,29.94,2.5,0.00,0.75

## Parse the pickup date time

In [45]:
df['tpep_pickup_datetime'] = pd.to_datetime(
    df['tpep_pickup_datetime']
)

display(df['tpep_pickup_datetime'])

0       2026-01-01 00:54:04
1       2026-01-01 00:34:04
2       2026-01-01 00:57:06
3       2026-01-01 00:15:22
4       2026-01-01 00:27:13
                ...
49995   2026-01-01 17:27:10
49996   2026-01-01 17:49:29
49997   2026-01-01 17:03:10
49998   2026-01-01 17:18:13
49999   2026-01-01 17:45:14
Name: tpep_pickup_datetime, Length: 50000, dtype: datetime64[us]

## extract the hours

In [46]:
df['hour'] = df['tpep_pickup_datetime'].dt.hour

display(df['hour'])

0         0
1         0
2         0
3         0
4         0
         ..
49995    17
49996    17
49997    17
49998    17
49999    17
Name: hour, Length: 50000, dtype: int32

## group by hour and average the tip

In [49]:
avg_hourly_tip = df.groupby('hour')['tip_amount'].mean()

display(avg_hourly_tip)

hour
0     3.410663
1     3.346816
2     3.237750
3     3.267645
4     3.105731
5     3.403228
6     3.473673
7     4.102529
8     3.739381
9     3.652016
10    3.346760
11    3.338315
12    3.282525
13    3.308559
14    3.518040
15    3.785902
16    3.938746
17    3.849081
23    0.666667
Name: tip_amount, dtype: float64

## clean up the results

In [50]:
avg_hourly_tip = avg_hourly_tip.round(2)

avg_hourly_tip = avg_hourly_tip.sort_index()

display(avg_hourly_tip)

hour
0     3.41
1     3.35
2     3.24
3     3.27
4     3.11
5     3.40
6     3.47
7     4.10
8     3.74
9     3.65
10    3.35
11    3.34
12    3.28
13    3.31
14    3.52
15    3.79
16    3.94
17    3.85
23    0.67
Name: tip_amount, dtype: float64